// NOTE: Boilerplate only.  Ignore this file.

// Package v1 contains API Schema definitions for the cluster v1 API group
// +k8s:deepcopy-gen=package,register
// +groupName=cluster.storageos.com
package v1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/runtime/scheme"
)

var (
	// SchemeGroupVersion is group version used to register these objects
	SchemeGroupVersion = schema.GroupVersion{Group: "storageos.com", Version: "v1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion}

	// AddToScheme adds all resources to the scheme
	// NOTE: This is not part of the operator-sdk scaffold and is added for
	// compatibility with clientset code generated by k8s/code-generator.
	AddToScheme = SchemeBuilder.AddToScheme
)
