/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/storageos/cluster-operator/pkg/apis/storageos/v1"
	scheme "github.com/storageos/cluster-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StorageOSUpgradesGetter has a method to return a StorageOSUpgradeInterface.
// A group's client should implement this interface.
type StorageOSUpgradesGetter interface {
	StorageOSUpgrades(namespace string) StorageOSUpgradeInterface
}

// StorageOSUpgradeInterface has methods to work with StorageOSUpgrade resources.
type StorageOSUpgradeInterface interface {
	Create(*v1.StorageOSUpgrade) (*v1.StorageOSUpgrade, error)
	Update(*v1.StorageOSUpgrade) (*v1.StorageOSUpgrade, error)
	UpdateStatus(*v1.StorageOSUpgrade) (*v1.StorageOSUpgrade, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.StorageOSUpgrade, error)
	List(opts metav1.ListOptions) (*v1.StorageOSUpgradeList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.StorageOSUpgrade, err error)
	StorageOSUpgradeExpansion
}

// storageOSUpgrades implements StorageOSUpgradeInterface
type storageOSUpgrades struct {
	client rest.Interface
	ns     string
}

// newStorageOSUpgrades returns a StorageOSUpgrades
func newStorageOSUpgrades(c *StorageosV1Client, namespace string) *storageOSUpgrades {
	return &storageOSUpgrades{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the storageOSUpgrade, and returns the corresponding storageOSUpgrade object, and an error if there is any.
func (c *storageOSUpgrades) Get(name string, options metav1.GetOptions) (result *v1.StorageOSUpgrade, err error) {
	result = &v1.StorageOSUpgrade{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storageosupgrades").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StorageOSUpgrades that match those selectors.
func (c *storageOSUpgrades) List(opts metav1.ListOptions) (result *v1.StorageOSUpgradeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.StorageOSUpgradeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storageosupgrades").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storageOSUpgrades.
func (c *storageOSUpgrades) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("storageosupgrades").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a storageOSUpgrade and creates it.  Returns the server's representation of the storageOSUpgrade, and an error, if there is any.
func (c *storageOSUpgrades) Create(storageOSUpgrade *v1.StorageOSUpgrade) (result *v1.StorageOSUpgrade, err error) {
	result = &v1.StorageOSUpgrade{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("storageosupgrades").
		Body(storageOSUpgrade).
		Do().
		Into(result)
	return
}

// Update takes the representation of a storageOSUpgrade and updates it. Returns the server's representation of the storageOSUpgrade, and an error, if there is any.
func (c *storageOSUpgrades) Update(storageOSUpgrade *v1.StorageOSUpgrade) (result *v1.StorageOSUpgrade, err error) {
	result = &v1.StorageOSUpgrade{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storageosupgrades").
		Name(storageOSUpgrade.Name).
		Body(storageOSUpgrade).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *storageOSUpgrades) UpdateStatus(storageOSUpgrade *v1.StorageOSUpgrade) (result *v1.StorageOSUpgrade, err error) {
	result = &v1.StorageOSUpgrade{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storageosupgrades").
		Name(storageOSUpgrade.Name).
		SubResource("status").
		Body(storageOSUpgrade).
		Do().
		Into(result)
	return
}

// Delete takes name of the storageOSUpgrade and deletes it. Returns an error if one occurs.
func (c *storageOSUpgrades) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storageosupgrades").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storageOSUpgrades) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storageosupgrades").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched storageOSUpgrade.
func (c *storageOSUpgrades) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.StorageOSUpgrade, err error) {
	result = &v1.StorageOSUpgrade{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("storageosupgrades").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
