/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/storageos/cluster-operator/pkg/apis/storageos/v1"
	scheme "github.com/storageos/cluster-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StorageOSClustersGetter has a method to return a StorageOSClusterInterface.
// A group's client should implement this interface.
type StorageOSClustersGetter interface {
	StorageOSClusters(namespace string) StorageOSClusterInterface
}

// StorageOSClusterInterface has methods to work with StorageOSCluster resources.
type StorageOSClusterInterface interface {
	Create(ctx context.Context, storageOSCluster *v1.StorageOSCluster, opts metav1.CreateOptions) (*v1.StorageOSCluster, error)
	Update(ctx context.Context, storageOSCluster *v1.StorageOSCluster, opts metav1.UpdateOptions) (*v1.StorageOSCluster, error)
	UpdateStatus(ctx context.Context, storageOSCluster *v1.StorageOSCluster, opts metav1.UpdateOptions) (*v1.StorageOSCluster, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.StorageOSCluster, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.StorageOSClusterList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StorageOSCluster, err error)
	StorageOSClusterExpansion
}

// storageOSClusters implements StorageOSClusterInterface
type storageOSClusters struct {
	client rest.Interface
	ns     string
}

// newStorageOSClusters returns a StorageOSClusters
func newStorageOSClusters(c *StorageosV1Client, namespace string) *storageOSClusters {
	return &storageOSClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the storageOSCluster, and returns the corresponding storageOSCluster object, and an error if there is any.
func (c *storageOSClusters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.StorageOSCluster, err error) {
	result = &v1.StorageOSCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storageosclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StorageOSClusters that match those selectors.
func (c *storageOSClusters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.StorageOSClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.StorageOSClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storageosclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storageOSClusters.
func (c *storageOSClusters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("storageosclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a storageOSCluster and creates it.  Returns the server's representation of the storageOSCluster, and an error, if there is any.
func (c *storageOSClusters) Create(ctx context.Context, storageOSCluster *v1.StorageOSCluster, opts metav1.CreateOptions) (result *v1.StorageOSCluster, err error) {
	result = &v1.StorageOSCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("storageosclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(storageOSCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a storageOSCluster and updates it. Returns the server's representation of the storageOSCluster, and an error, if there is any.
func (c *storageOSClusters) Update(ctx context.Context, storageOSCluster *v1.StorageOSCluster, opts metav1.UpdateOptions) (result *v1.StorageOSCluster, err error) {
	result = &v1.StorageOSCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storageosclusters").
		Name(storageOSCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(storageOSCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *storageOSClusters) UpdateStatus(ctx context.Context, storageOSCluster *v1.StorageOSCluster, opts metav1.UpdateOptions) (result *v1.StorageOSCluster, err error) {
	result = &v1.StorageOSCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storageosclusters").
		Name(storageOSCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(storageOSCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the storageOSCluster and deletes it. Returns an error if one occurs.
func (c *storageOSClusters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storageosclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storageOSClusters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storageosclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched storageOSCluster.
func (c *storageOSClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StorageOSCluster, err error) {
	result = &v1.StorageOSCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("storageosclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
