/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	storageosv1 "github.com/storageos/cluster-operator/pkg/apis/storageos/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNFSServers implements NFSServerInterface
type FakeNFSServers struct {
	Fake *FakeStorageosV1
	ns   string
}

var nfsserversResource = schema.GroupVersionResource{Group: "storageos.com", Version: "v1", Resource: "nfsservers"}

var nfsserversKind = schema.GroupVersionKind{Group: "storageos.com", Version: "v1", Kind: "NFSServer"}

// Get takes name of the nFSServer, and returns the corresponding nFSServer object, and an error if there is any.
func (c *FakeNFSServers) Get(ctx context.Context, name string, options v1.GetOptions) (result *storageosv1.NFSServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nfsserversResource, c.ns, name), &storageosv1.NFSServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*storageosv1.NFSServer), err
}

// List takes label and field selectors, and returns the list of NFSServers that match those selectors.
func (c *FakeNFSServers) List(ctx context.Context, opts v1.ListOptions) (result *storageosv1.NFSServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nfsserversResource, nfsserversKind, c.ns, opts), &storageosv1.NFSServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &storageosv1.NFSServerList{ListMeta: obj.(*storageosv1.NFSServerList).ListMeta}
	for _, item := range obj.(*storageosv1.NFSServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nFSServers.
func (c *FakeNFSServers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nfsserversResource, c.ns, opts))

}

// Create takes the representation of a nFSServer and creates it.  Returns the server's representation of the nFSServer, and an error, if there is any.
func (c *FakeNFSServers) Create(ctx context.Context, nFSServer *storageosv1.NFSServer, opts v1.CreateOptions) (result *storageosv1.NFSServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nfsserversResource, c.ns, nFSServer), &storageosv1.NFSServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*storageosv1.NFSServer), err
}

// Update takes the representation of a nFSServer and updates it. Returns the server's representation of the nFSServer, and an error, if there is any.
func (c *FakeNFSServers) Update(ctx context.Context, nFSServer *storageosv1.NFSServer, opts v1.UpdateOptions) (result *storageosv1.NFSServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nfsserversResource, c.ns, nFSServer), &storageosv1.NFSServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*storageosv1.NFSServer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNFSServers) UpdateStatus(ctx context.Context, nFSServer *storageosv1.NFSServer, opts v1.UpdateOptions) (*storageosv1.NFSServer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nfsserversResource, "status", c.ns, nFSServer), &storageosv1.NFSServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*storageosv1.NFSServer), err
}

// Delete takes name of the nFSServer and deletes it. Returns an error if one occurs.
func (c *FakeNFSServers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nfsserversResource, c.ns, name), &storageosv1.NFSServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNFSServers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nfsserversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &storageosv1.NFSServerList{})
	return err
}

// Patch applies the patch and returns the patched nFSServer.
func (c *FakeNFSServers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *storageosv1.NFSServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nfsserversResource, c.ns, name, pt, data, subresources...), &storageosv1.NFSServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*storageosv1.NFSServer), err
}
